# Generated by Django 5.2 on 2025-04-15 14:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('is_public', models.BooleanField(default=False, help_text='Property becomes public when approved by admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.CharField(max_length=100)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('county', models.CharField(blank=True, max_length=100, null=True)),
                ('parish', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('number_or_lot', models.CharField(blank=True, max_length=50, null=True)),
                ('floor_or_apartment', models.CharField(blank=True, max_length=50, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House')], max_length=20)),
                ('number_of_rooms', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)])),
                ('gross_area', models.DecimalField(decimal_places=2, help_text='Area in square meters', max_digits=10)),
                ('construction_year', models.IntegerField(blank=True, null=True)),
                ('condition', models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('needs_renovation', 'Needs Renovation')], max_length=20)),
                ('has_garage', models.BooleanField(default=False)),
                ('has_elevator', models.BooleanField(default=False)),
                ('has_air_conditioning', models.BooleanField(default=False)),
                ('has_private_garden', models.BooleanField(default=False)),
                ('has_private_pool', models.BooleanField(default=False)),
                ('has_storage', models.BooleanField(default=False)),
                ('has_basement', models.BooleanField(default=False)),
                ('has_terrace', models.BooleanField(default=False)),
                ('urgent_sale', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=5)),
                ('estimated_value', models.DecimalField(decimal_places=2, help_text='Value in euros', max_digits=12)),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_surname', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
                ('observations', models.TextField(blank=True, null=True)),
                ('how_found', models.CharField(choices=[('facebook', 'Facebook'), ('google', 'Google'), ('friend', 'Friend'), ('other', 'Other')], max_length=50)),
                ('marketing_consent', models.BooleanField(default=False)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(default='CPU', help_text='CPU - Caderneta Predial Urbana', max_length=50)),
                ('file', models.FileField(upload_to='property_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='investment.property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.IntegerField(default=0)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='investment.property')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
